### ISSUE TITLE
User guide is not being updated on Github

### ISSUE THREAD

**Issue by powelli** [awsdocs/aws-elemental-medialive-user-guide#2]
Following the link to Github from the MediaLive documentation online at https://docs.aws.amazon.com/medialive/latest/ug/what-is.html leads to this repository, but the documentation here is over a year old.

Was hoping to watch this repo to be notified on documentation updates.

**Comment by zidanemoggy** [comment]
Hi Simon, I just updated this repository. Sorry for the delay in responding. 
Catherine
