### ISSUE TITLE
Locations should be of the form https://<hostname>/<path>

### ISSUE THREAD

**Issue by alzin** [awsdocs/aws-elemental-medialive-user-guide#4]
I am trying to use AWS Elemental MediaLive to establish an RTMP Livestream service and to be able to get the video of a DJI drone using iOS app being hosted on transfer livestream from the drone camera,

However, I think I did each step correctly until an error comes up which is related to creating a new Channel:

Validation Errors
outputGroups[0].outputGroupSettings.destination.uri
Locations should be of the form https://<hostname>/<path>

I am using HLS  Output Group and I need to insert two HLS group desitnation A and B URL that is the created containers under the Storage containers section.

Then, under the HLS settings I specified the name and the CDN Settings as HLS webdav.

And as Input attachment I got an RTMP input created that has also two destinations A and B and of course I attached it already to the new Channel that I am trying to create.

However, it seems to me that the error is related to the **Locations** section that has info about:
Base URL Manifest
Base URL Manifest B 
.
.
.

Please let me get help in pointing out if I need to fill in the Location textview or I need to edit something within the settings!!?

**Comment by zidanemoggy** [comment]
Hi Alzin, could you send a bit more info:
- an example of the value you're putting in one of the HLS group destination URL fields. 
- details on the downstream system you are using. We are a bit confused by your reference to the "Storage containers" section.

I am pretty sure that the Base URL manifest fields are not involved in this error.
By the way, I am currently working on a revision to this section, hopefully to make the purpose of all these fields clearer.
Catherine

**Comment by alzin** [comment]
@zidanemoggy Thank you for helping out!

These are the settings that I am using, I hide some important IP and numbers for security.
Please note that I am using this tutorial by AWS Media Blog:
https://aws.amazon.com/blogs/media/part1-how-to-send-live-video-to-aws-elemental-mediastore/

<img width="1136" alt="1" src="https://user-images.githubusercontent.com/35889862/74791729-a87a9c80-52fe-11ea-9156-51befb05d189.png">

<img width="1392" alt="2" src="https://user-images.githubusercontent.com/35889862/74791752-b7614f00-52fe-11ea-86b2-ee71d48f230e.png">

<img width="1392" alt="3" src="https://user-images.githubusercontent.com/35889862/74791757-b9c3a900-52fe-11ea-953b-31cbff180799.png">

<img width="1392" alt="4" src="https://user-images.githubusercontent.com/35889862/74791763-bcbe9980-52fe-11ea-958a-f21fa1306293.png">

<img width="1392" alt="5" src="https://user-images.githubusercontent.com/35889862/74791769-c2b47a80-52fe-11ea-80dd-13d22ac24ef1.png">

<img width="1392" alt="6" src="https://user-images.githubusercontent.com/35889862/74791776-c7792e80-52fe-11ea-9031-97effeae4c4b.png">

<img width="1392" alt="7" src="https://user-images.githubusercontent.com/35889862/74791777-c9db8880-52fe-11ea-917c-fd6a06a537a1.png">

**Comment by zidanemoggy** [comment]
Hi Alzin, I think the solution is pretty easy. If you are sending to mediastore, you must choose "Hls media store" in the CDN field. That tells MediaLive to verify that the other info that you enter is all good for MediaStore as the destination.

Then in the URL, you need to use the protocol "mediastoressl://". 

You can read about this in https://docs.aws.amazon.com/medialive/latest/ug/about-hls-file-locations.html

**Comment by alzin** [comment]
@zidanemoggy Thank you very much for your support!

Indeed, I wrote the URL like the following:

mediastoressl://6o3jvzaieizvw.data.mediastore.ap-northeast-1.amazonaws.com/LiveVideoGhaith

This means that in the end, I had to add the 'Storage Container's names' to it to make it work.
So, I created the Channel successfully and I start pushing the live video from the drone using
 rtmp://13.230.206:1935/stream1/a

However, I can't know which URL that I need to keep tracking my video stream online on the web
I tried the following one but it seems to be the fault one!!:

https://6o3jvzaieizv.data.mediastore.ap-northeast-1.amazonaws.com

Please refer to the correct URL structure if you know it!?

**Comment by zidanemoggy** [comment]
Hi Alzin, I assume you are trying to look at your mediastore container on the MediaStore conole, in order to see the stream hitting the container. You need to go to the container called LiveVideoGaith and you should see ts segments (files) being added.
You might not have policies on MediaStore. Read this https://docs.aws.amazon.com/mediastore/latest/ug/setting-up-IAM-users-create-nonadmin.html.
It doesn't look like your issue is a documentation issue in MediaLive, so if you have any more problems, I suggest that you contact Support through the link on the MediaStore console.
